/*
 * @lc app=leetcode id=389 lang=cpp
 *
 * [389] Find the Difference
 *
 * https://leetcode.com/problems/find-the-difference/description/
 *
 * algorithms
 * Easy (53.41%)
 * Likes:    531
 * Dislikes: 233
 * Total Accepted:    151.5K
 * Total Submissions: 283.8K
 * Testcase Example:  '"abcd"\n"abcde"'
 *
 * 
 * Given two strings s and t which consist of only lowercase letters.
 * 
 * String t is generated by random shuffling string s and then add one more
 * letter at a random position.
 * 
 * Find the letter that was added in t.
 * 
 * Example:
 * 
 * Input:
 * s = "abcd"
 * t = "abcde"
 * 
 * Output:
 * e
 * 
 * Explanation:
 * 'e' is the letter that was added.
 * 
 */
class Solution {
public:
    char findTheDifference(string s, string t) {
        char diff = 0;
        for(int i = 0; i < s.size(); i++) {
            diff ^= s[i];
        }
        for(int i = 0; i < t.size(); i++) {
            diff ^= t[i];
        }
        return diff;
    }
};

